parameters:
  service-dir:
    default: "sdk/servicenetworking"
emit:
  - "@azure-tools/typespec-java"
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
options:
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-servicenetworking"
    namespace: com.azure.resourcemanager.servicenetworking
    examples-directory: examples
    fluent: lite
    dev-options:
      # debug: true
      generate-code-model: true
