parameters:
  service-dir:
    default: "sdk/containerstorage"
emit:
  - '@azure-tools/typespec-autorest'
  - '@azure-tools/typespec-java'
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
  disable:
    "@azure-tools/typespec-azure-resource-manager/arm-common-types-version": "New rule"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/containerstorage.json"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-containerstorage"
    namespace: com.azure.resourcemanager.containerstorage
    examples-directory: examples
    generate-samples: false
    generate-tests: false
    dev-options:
      # debug: true
      generate-code-model: true
      java-temp-dir: C:\\Users\\xiaofeicao\\Desktop\\code-model
